---
title: "Chapter 2: Python and Programming"
format:
  html:
    toc: true
    code-fold: false
  gfm:
    toc: false

execute: 
  error: true
engine: jupyter
---
## Notes

### What makes a Programmer?

- The ability to solve a program yourself
- Convert that solution into something the computer understands

#### Programming and Problems

- Programming is problem solving
- A key part of programming is properly defining the problem and scope
  - In real projects this may take the form of a *functional design specification*
- A well defined problem is easy to reason about

::: {.callout-tip}
**Specifications must always exist**

One should never write a program without getting a solid specification first. Defining a specification is essential even (or perhaps especially) when I do a job for a friend
:::

- Modern design techniques emphasise *prototyping*
  - The use of successive versions to solicit customer feedback

#### Programmers and People

- The best programmers are also good communicators
- Effective communication extends to writing
  - Helps write code that more clearly articulates your point

::: {.callout-tip}
**Communication leads to the most interesting work**

Interesting tasks go to developers who are good communicators. They can articulate their ideas and liase with customers
:::

### Computers as Data Processors

#### Machines, Computers and Us

- Computers automate instructions
  - They follow given instructions
  - Convert input data into output data
- Computers are typically unware of the veracity of their data
  - No inate ability to question, or *error recover*

```{mermaid}
block-beta
    columns 3
    space
    title["Examples of Typical Data-Processing Applications"]
    space

    block:Input
    columns 1
        Inputs
        radio["Radio Signals and Touchpad"]
        car["Temperature, Pressures, Throttle"]
        game["Gamepad"]
    end

    block:Middle
    columns 1
        space
        phone["Mobile Phone"]
        carMiddle["Car"]
        console["Console"]
    end

    block:Output
    columns 1
        Outputs
        phoneOut["Sound, Pictures"]
        carOut["Fuel Injector, Ignition timings"]
        consoleOut["Gameplay"]
    end

    radio-->phone
    phone-->phoneOut
    car-->carMiddle
    carMiddle-->carOut
    game-->console
    console-->consoleOut

classDef BG stroke:transparent, fill:transparent
class title BG
class Inputs BG
class Outputs BG
```

:::{.callout-note}
**Software might be a matter of life or death**

Seemingly innocent programs can have real consequences. E.g. a program that calculates drug dosages may be used by a doctor. [Therac-25](https://en.wikipedia.org/wiki/Therac-25) is the classic example.
:::

#### Programs as Data Processors

```{mermaid}
---
title: Computers as Data Processors
config:
  flowchart:
    htmlLabels: false
---
flowchart LR

input(("Input"))
computer["Computer"]
output(("Output"))

input-->computer
computer-->output
```

- As discussed computers can be seen as data transformers
- We can view this as similar to following a recipe

```{mermaid}
---
title: Recipes as Programs
config:
  flowchart:
    htmlLabels: false
---
flowchart LR

flour(("Flour"))
sugar(("Sugar"))
milk(("Milk"))
eggs(("Eggs"))

human["Human following
     recipe"]

cake(("Cake"))

flour-->human
sugar-->human
milk-->human
eggs-->human

human-->cake
```

#### Python as a Data Processor

- Python is effectively one of the ways we can make a computer do things

```{mermaid}
---
title: Python as a Data Processor
config:
  flowchart:
    htmlLabels: false
---
flowchart LR

input(("Python 
        Commands"))
computer["Python Command Shell"]
output(("Results"))

input-->computer
computer-->output
```

- Commands are the *input* which are processed by the `python command shell` (*the computer*) and turned into results (*output*)

### Example: Playing with the Shell

- Start up a python interpreter and run the following, explaining was happens in each case
    1. `hello` - An error, an arbitrary word is unrecognised

  ```{python}
  hello
  ```

    2. `2` - `2` is echoed back out

  ```{python}
  2
  ```

    3. `2+2` - `4`, the arithmetic is performed

  ```{python}
  2 + 2
  ```

- `2 + 2` in the previous example is a representation of an *expression*
- Python evaluates expressions
- The `2`'s are called *operands* - they are consumed by *operators* like `+` to produce results

:::{.callout-warning}
As seen in the previous example, when invalid code is entered into the shell, an error message occurs. The same happens for an incomplete expression. e.g. the following is a shell sequence,

```{python}
2+
```

:::

### Exercise: Python Expressions

1. *What do you think would happen if you tried to evaluate `2+3*4`?*

We would expect `14` from the basic mathematical order of operations. Plugging this into the shell,

```{python}
2 + 3 * 4
```

2. *What do you think would happen if you tried to evaluate `(2+3)*4`?*

We would expect `20` from the basic mathematical order of operations. Plugging this into the shell,

```{python}
(2 + 3) * 4
```

3. *What do you think would happen if you tried to evaluate `(2+3*4`?*

We might expect a syntax error, instead the interpreter, simply goes to a new line, and waits for us to enter the matching parenthesis. One such sequence in the shell might be,

```{python}
(2 + 3 * 4
```

Try this one yourself! Note that if you use a jupyter notebook like environment, like has been used for rendering the code in these notes, you might instead get a `SyntaxError: Incomplete Input`

4. *What do you think would happen if you tried to evaluate `)2+3*4`?*

If we see a right parenthesis before a left parenthesis there is no way to retroactively go back and fix the missing left, like in the previous case were the shell hung. So here we would expect a syntax error.

```{python}
)2+3*4
```

#### Python as a Scripting Language

- We can use the interpreter like this to work line by line because python is a "scripting" language
  - i.e. The program reads a line and then *interprets* the output

:::{.callout-note}
**Not all languages are scripting languages**

Not all languages are scripting languages. Some are converted to low-level hardware instructions. This is called *compilation*, and in place of an interpreter it requires a *compiler* to convert the code. Compiled programs are typically faster, since they can be *optimised*
:::

### Data and Information

- Computers fundamentally represent data as $0$ or $1$ in binary
  - We build up layers of abstract that let us handle concepts like *numbers*, *characters* and *strings* of text
- **Data** can be regarded as the *stored values* representing *information*
- **Information** is thus the interpretation of data, to mean *something*

#### Data Processing in Python

- See [Example: Work with Text in Python](#work-with-text-in-python)
- See [Ex2.5](#exercise-25), [Ex 2.6](#exercise-26), [Ex2.7](#exercise-27), [Ex2.8](#exercise-28)

#### Text and Numbers as Data Types

- Python seperates numerical data (e.g. `2`) from text data (e.g. `'2'`)
  - Numerics and text are stored differently
- Behaviour of operators depends on the data types fed into them as operands

### Working with Python Functions

- A *function* is behaviour with a distinct name
  - e.g. "Move left" is name for a distinct behaviour
- Python comes bundled with a number of *built-in* functions

:::{.callout-important}
**Functions are a critical part of programming languages**

Learning a new language often involves learning the functions it natively supports.
:::

#### The `ord` function

- `ord` is a short name for *ordinal value*
  - Built-in function, mean's *"give me the number representing this character"*

  - Let's examine the use,

    ```python
    >>> ord('W')
    87
    ```

- See [Example: Investigate Text Representation using `ord`](#investigate-text-representation-using-ord)

- Observe a function is called with the structure,

```{mermaid}
block-beta
    columns 4
    space
    title["Function Call Structure"]:2
    space

    block:name
    columns 1
        ord["ord"]
        functionName["function name"]
        fndescr["(thing we want done)"]
    end

    block:leftParenthesis
    columns 1
        leftP["("]
        leftPname["Parenthesis"]
        space
    end

    block:argumentblock
    columns 1
        argument["'W'"]
        argumentName["argument"]
        argumentDescr["(thing to give function)"]
    end

    block:rightParenthesis
    columns 1
        rightP[")"]
        rightPname["Parenthesis"]
        space
    end


classDef BG stroke:transparent, fill:transparent
class title BG
class ord BG
class functionName BG
class fndescr BG
class leftP BG
class leftPname BG
class argument BG
class argumentName BG
class argumentDescr BG
class rightP BG
class rightPname BG
```

#### The `chr` function

- The `chr` function is the counterpart to `ord`
  - Converts numbers to text

```{python}
chr(87)
```

- See [Example: Convert Numbers to text using `chr`](#convert-numbers-to-text-using-chr)

- International standards govern text representation
  - However, these standards may or may not be followed by older languages or software

#### Investigate data storage using `bin`

- As mentioned before, computers store data in binary
- Each $0$ or $1$ is called a *bit*, a byte is typically a collection of $8$ bits, and the smallest addressable unit of memory
- Bytes can be grouped together to represent larger blocks of data
- `bin` converts a number to a string containing it's binary representation

```{python}
bin(87)
```

- The prefix `0b` indicates that the remaining suffix is the binary representation of a number

- See [Ex2.9](#exercise-29)

## Summary

- Computers view data as binary
- Computers process input data into output data
- Humans intepret data as *information*
- Computers do not naturally understand meaningful or nonsense input or output
- A program is the process of telling a computer how to convert input data into output data
  - Programming languages are a way to write these programs that the computer understands
- Python is one such language
  - It can also be viewed as a program that takes language statements, and then converts them to orders for the computer to carry out
- Programmers create sequences of instructions to describe the task a computer needs to carry out
  - Good code means knowing what the code needs to do
  - Formal requirements solicitation and communication skills are key for programmers

## Question and Answers

1. *Would a computer "know" that its stupid for someone to have an age of* $-20$?
    - No. As far as the computer is concerned, the age valueis just a pattern of bits that represents a number. If we want a computer to reject negative ages, we must actually build that understanding into the program
2. *If the output from a program is settings for the fuel-injection system on a car, is the output data or information?*
    - As soon as something starts acting on data, it becomes information. A human being is not doing anything with these values, but they will cause the speed of the engine to change, which might affect humans, so this makes the output information rather than data by the authors opinion
3. *Is the computer stupid because it can't understand English?*
    - No, english can be a quite ambiguous languge. The legal profession is an example of somewhere were debate over the semantics of language is tricky
4. *If I don't know how to solve a problem, can I write a program to do it?*
    - No, you need to understand the solution before you can write it and make sure that it does exactly what you want it to do
5. *Is it sensible to assume the customer measures everything in inches?*
    - It's never sensible to assume anything about a project. Every assumption increases the chance of a potential disaster
6. *If the program does the wrong thing, is it my fault or the customer's fault?*

| **Specification?** | **Program?** | **Whose Fault?** |
|--------------------|--------------|------------------|
| Right              | Wrong        | Programmer       |
| Wrong              | Right        | Customer         |
| Wrong              | Wrong        | Everyone         |
